apiVersion: apps/v1
kind: Deployment
metadata:
  name: david-deployment
  labels:
    app: david
spec:
  replicas: 3
  selector:
    matchLabels:
      app: david
  template:
    metadata:
      labels:
        app: david
    spec:
      containers:
      - name: david
        image: bit1010/david:latest
        ports:
        - containerPort: 80